### ISSUE TITLE
Where to find settings.yaml

### ISSUE THREAD

**Issue by pellejacobs** [ttreeagency/ChromeLogger#1]
Hi,
Could you be more specific concerning the changes to the settings.yaml file? I'm not really sure where to find this file. 
Thanks!

**Comment by dfeyer** [comment]
The file Settings.yaml is located in your package Configuration directory. You can also use the distribution Configuration directory, check the official documentation here:
http://docs.typo3.org/flow/TYPO3FlowDocumentation/TheDefinitiveGuide/PartIII/Configuration.html
